### ISSUE TITLE
grisu audit

### ISSUE THREAD

**Issue by yuriyh** [grisu/grisu#13]
we should be able to generate statistics, for number of users, jobs, throughput etc.

**Comment by ndjones** [comment]
Some of these are being collected in gricli - refer grisu/gricli#81 - perhaps we should discuss a standard approach, destination for logging, format

**Comment by makkus** [comment]
Yes, that'd be good. 

To be honest, I have no idea where to start, what exactly needs to be done. At the moment we have debug and error log messages. Where should we go from there?

I will add debug messages to important backend API methods that shows when/how they are called. I thought of assigning logs like that to the "info" log4j-level so we can more easily parse logs. Does that make sense?

Is there a format the log strings should have? Sorry for being so daft, but I really don't have a proper grasp of how that should be done and where we want to end up and what is involved...

**Comment by ndjones** [comment]
Is this issue meant to track what we log, or suggesting that we need to setup an audit / analysis approach? If the latter, then it's not a grisu issue. If the former, then Yuriy to itemise all specific events to log.

**Comment by makkus** [comment]
@yuriyh, can you have a look and update/close this (or move from milestone if appropriate)?

Would like to release Grisu milestone before releasing 2nd Gricli rc...

**Comment by yuriyh** [comment]
i move it to next milestone.

**Comment by ndjones** [comment]
has gene partly done this already?

**Comment by yuriyh** [comment]
not really, this issue is intended for server side logging.

**Comment by makkus** [comment]
I'm having a look at monitoring (and benchmarking) remote method invocations using Spring:

http://www.javaworld.com/community/node/3763

Should be easy enough.

**Comment by makkus** [comment]
Ok, intercepting all method invocations now, will appear in log like:

DEBUG 2011-09-07 01:24:13,883 [TP-Processor5][] grisu.control.util.AuditAdvice - Entering method: getAllSubmissionLocationsForFqan arguments: /nz user: DC=nz,DC=org,DC=bestgrid,DC=slcs,O=The University of Auckland,CN=Markus Binsteiner _bK32o4Lh58A3vo9kKBcoKrJ7ZY time: 1315315453883

DEBUG 2011-09-07 01:24:13,900 [TP-Processor5][] grisu.control.util.AuditAdvice - Finished method: getAllSubmissionLocationsForFqan arguments: /nz user: DC=nz,DC=org,DC=bestgrid,DC=slcs,O=The University of Auckland,CN=Markus Binsteiner _bK32o4Lh58A3vo9kKBcoKrJ7ZY time: 1315315453900 duration: 17

Happy to change log message so it can be parsed with existing script if necessary. 

This can be tested on dev backend.

**Comment by makkus** [comment]
Added heaps of log statements to next release...
