### ISSUE TITLE
support environment variables in jobs

### ISSUE THREAD

**Issue by yuriyh** [grisu/grisu#18]
globus allows to set environment variables via rsl tags. Useful for mpi jobs where these variables are not carried over when added to shell script.

Also, it could be useful to publish extra variables for every job: job number for batch job submissions (to support simple job arrays),  location for common files, location for individual files. So that job submission looks the same regardless of whether it is batch or normal job:

${GRISU_JOB_DIR}/common-file-executable ${GRISU_SUBJOB_DIR}/input-file-specific-for-job

**Comment by ndjones** [comment]
what would this require, cost wise? It would seem very valuable based on your description

**Comment by makkus** [comment]
That should be comparatively cheap. Should we move it to next milestone?

**Comment by makkus** [comment]
Yuriy, I assigned you to the ticket because of the missing GT5Submitter support for that. JobObject can be queried for set environment variables.

Didn't change batchjob to use that, for now. Probaably not that important to change that just yet since it works the other way too...

**Comment by yuriyh** [comment]
either something is wrong with my client code or there is a bug:

environment = {BHAHAHAHHAAHAHAHA=somevalue, ZBAHAHAHAAHAHA=somevalue}

result:

<environment>
<name>BHAHAHAHHAAHAHAHA</name>
<value>somevalue, ZBAHAHAHAAHAHA=somevalue</value>
</environment>

I set them by 

props = new hashtable
env = new hashtable
env.put(var1,value1)
env.put(var2,value2)
props.put(JobSubmissionProperties.ENVIRONMENT_VARIABLES, env.toString())
job = new JobObject(si, props)

**Comment by makkus** [comment]
Sorry, not really sure I'm getting your pseudo-code.

But if you really need to use this constructor and don't want to add the environment variables one by one or set the environment variables on the job object, then you need to convert the string-map into a string the proper way. Not sure what toString() does here...

There's a class grisu.utils.StringHelpers that has got a method mapToString....

There might be still a bug though, I didn't test setting more than one variable yesterday, so tell me how that goes...

**Comment by yuriyh** [comment]
ok, understood now. it works, both for single and multiple variables.
