### ISSUE TITLE
store job metadata in archived location

### ISSUE THREAD

**Issue by yuriyh** [grisu/grisu#19]
when job is archived, extra file with its properties is stored as well.

This way we can write a script that will convert this data into irods metadata on user request, so that job description, name, time,  rsl description will be available forever.

**Comment by ndjones** [comment]
should also log that the job has been archived - refer grisu/gricli#81

**Comment by ndjones** [comment]
Yep, agree - the action of being archived would be a separate record,
you're right. And the completed job metadata would be logged, on
completion.

**Comment by makkus** [comment]
Yes. That would only be status anyway, all the rest we can get when submitting.
Would be nice to be able to have time of completion, but best we can do is time of when Grisu found out that job was finished. Which could be one week after job actually finished, depending on when user logs in after that...

**Comment by makkus** [comment]
So, that seems to be not really an issue, just a statement? We already store job metadata when job is archived...

Can I close?
