### ISSUE TITLE
proxy lifetime for grisu jobs is always 1 hour

### ISSUE THREAD

**Issue by yuriyh** [grisu/grisu#27]
Tried to figure out what happens to job by modifying proxyLifetime user property... And discovered something interesting - proxy lifetime is always 1 hour - regardless of whether that variable is set. 

And quick check for proxy lifetimes at auckland gateways seems to indicate that grisu always behaved this way. 

Because in gram5 job audit does not work properly when job exceeds its proxy lifetime, this becomes a major bug...

**Comment by yuriyh** [comment]
this one seems to be partially related to default myproxy lifetime setting in backend properties. If I increase it, so does delegated proxy walltime. 

Unfortunately submitProxyLifetime setting for grisu seems to have no effect.

**Comment by makkus** [comment]
I changed proxy lifetime on both test and dev backends to 10 days. This should also up submitProxyLifetime.

If you use a local backend, you can adjust submitProxyLifetime manually by using the setDebugProperties method in AbstractServiceInterface

**Comment by ndjones** [comment]
How major is this Yuriy? All users with jobs running beyond 1 hour?

Any idea on fixes?

**Comment by yuriyh** [comment]
fixed, by backend configuration. now it is 10 days
