### ISSUE TITLE
Check whether backend re-queries job statuses after getting back "NO_SUCH_JOB" from globus

### ISSUE THREAD

**Issue by makkus** [grisu/grisu#3]
It may be that the backend assumes that a job is lost once it gets "NO_SUCH_JOB" from a globus endpoint. But it should in fact query again, since the issue of why the job couldn't be found (authentication?) could be fixed in the meantime...

**Comment by ndjones** [comment]
@yuriyh - as you are taking a look at job status related issues, could you review this one too?

**Comment by makkus** [comment]
Oh, sorry. I already checked that. Can be closed.
