### ISSUE TITLE
Switch to logback logger

### ISSUE THREAD

**Issue by makkus** [grisu/grisu#35]
Should help with all the new logging requirements we have. It's also faster than log4j.

http://logback.qos.ch/reasonsToSwitch.html

**Comment by ndjones** [comment]
For this release? :)

**Comment by makkus** [comment]
Didn't plan to, but could. Just wanted the thing logged, no pun intended...
Shouldn't be too hard, there is a compatibility layer so we don't need to change all of our log statements...

**Comment by makkus** [comment]
Done.
