### ISSUE TITLE
Support grid:// virtual urls for job input

### ISSUE THREAD

**Issue by makkus** [grisu/grisu#4]
Currently, one can only use local or gsiftp urls when adding input files for a job.

**Comment by yuriyh** [comment]
just tried - are you sure, gsiftp:// urls are supported? it does nothing to non-local files, in stageFiles() method. 
And no files are moved, when i submit jobs via gricli.

the only difference between grid:// and gsiftp:// is that isLocal returns true for grid:// and job reports error.

**Comment by makkus** [comment]
Ok. This is a bug. Somehow the stageing elements seem to disappear when converting the jobobject to jsdl. Investigating...

**Comment by makkus** [comment]
All right, what should we do? If I have a url like: 

grid://groups/nz/nesi/reindent.py

it could resolve to several "real"urls. Could be in Auckland, in Canterbury or wherever else a filesystem exists that is mapped to /nz/nesi group. I can implement something so it looks up all possible parent directories and uses the first really existing file with the filename.
Or I throw an exception whenever there are 2 or more filesystem referenced by such a virtual url.
If you list a directory and get back a list of GridFile objects, you can inspect those, they usually have a list of "real" gridftp urls associated with them that indicate where the file actually is.
That obviously doesn't work if you provide the virtual url as input file url directly...

**Comment by yuriyh** [comment]
failure on duplicates would be too much hassle for users: most likely two files with the same path are equivalent.  And if this is not the case, i may implement command that gets gsiftp urls from virtual ones so user can decide. 

minor issue anyway, as most users would only have one filesystem under VO.

**Comment by makkus** [comment]
Hm. Still an issue. Bloody thing copies something, but when copying is finished what is supposed to be a file ends up being a directory.... It's like turning water into wine, just not useful...
Will fix tomorrow.
