### ISSUE TITLE
'print job JOBID' prints stale job status

### ISSUE THREAD

**Issue by mondkaefer** [grisu/grisu#42]
Seems like 'print job JOBID' prints stale job status information.

'print job JOBID' for a job that finished processing doesn't show status as Done, but as Pending
'print job JOBID status' shows the right thing. 
'print jobs' shows the right thing. 

After executing 'print job JOBID status' or 'print jobs': 'print job JOBID' shows the correct status as well.
Also: if I 'wait job JOBID' after submission, a subsequent 'print job JOBID' prints the correct status.

**Comment by makkus** [comment]
This is a gricli issue, not a grisu one. Fixed in gricli code.
