### ISSUE TITLE
Add date to log statements

### ISSUE THREAD

**Issue by mondkaefer** [grisu/grisu#43]
grisu backend log entries look like this:

09:55:55.786 [INFO] [TP-Processor5]                [AuditAdvice] tid=[-6456071180939160650] csid=[mfel395_1329684942565] cmdid=[print_1329684955247] user=[Martin Feller g4eVuEfx26afmQq3O3mQdUzdiu8] - Finishing method: method=[getJobStatus] arguments=[gricli] result=[0] time=[1329684955786] duration=[497] open_calls=[0]

In addition to time information: add date information

**Comment by mondkaefer** [comment]
A comment on this: 
As Nick points out, we implicitly have date information available in the 'time' element of the log entry, which is a Unix timestamp (time in seconds, since 1/1/1970 (GMT)).
But I'd still find it useful to have a human readable date entry in there. Or we could as well remove the human readable time information from the logs and just work with the Unix timestamp. But maybe that would make debugging a bit hard, if there is no tool support to transform timestamps into date and time?

**Comment by makkus** [comment]
If we do our log-watching in Graylog, we'd see the proper dates and wouldn't overload the original logs. Would that be enough?

**Comment by mondkaefer** [comment]
I think it would be useful to be able to look at logs in a terminal, and not rely on Graylog to be able to figure out at what time a log statement was written; why create a dependency if it's not really required?
If overloading is considered bad, I'd rather replace the timestamp field with a human-readable date+time instead.

**Comment by makkus** [comment]
Ah, hold on. Mixed that up. The unix timestamp is not actually in the file that is written by the grisu backend, only the time.

I guess this is more an issue how logging is configured for the services we want to watch. For example the production backend is configured to send logs to graylog directly and also to write out into user-specific files in /var/log/grisu. So all we need to do here is change /etc/grisu/logback.xml (and restart tomcat).

P.S. you should really have a look at graylog (once it's ready again :-) ) it's way nicer than watching logs on a console

**Comment by mondkaefer** [comment]
Duh, right :) We should adjust the logback configuration to include the date then.
I will have a look at logback. But your comment ("once it's ready again") is exactly my point to not rely on it too much, at least not to a point where you have crippled local logs.

**Comment by makkus** [comment]
Added day and month to logback.xml on compute.services.bestgrid.org and also on the login node for gricli. compute.services might need a restart before it comes into effect.
