### ISSUE TITLE
RSL attribute stdin is set to job directory

### ISSUE THREAD

**Issue by yhal003** [grisu/grisu#46]
regression in grisu-core/src/main/java/grisu/backend/model/job/gt5/RSLFactory.java

when stdin/stdout/stderr is set, it uses whenNotBlank(workingDirectory + value...) but workingDirectory is never blank. 
Fix is easy (just remove workingDirecoty bit) but I assume it was added for a reason. Markus, can you have a look please?

**Comment by mondkaefer** [comment]
This results in Python jobs failing with the message "Fatal Python error: <stdin> is a directory"
(python /home/mfel395/test.py  < /home/mfel395/active-jobs/gricli_002/)

**Comment by mondkaefer** [comment]
I think the motivation for adding workingDirectory to the path of std\* elements was to avoid creation of stdout.txt and stderr.txt in ${HOME}, which is a good thing. The fix would probably be to check if JsdlHelpers.getPosixStandardInput(jsdl) is blank and still add workingDirectory to the path if it's not blank
